FROM node:18.14.2-alpine3.16 AS node

WORKDIR /usr/src/app
COPY package.json ./
RUN npm i 

COPY ./ ./
RUN npm run build

FROM nginx

COPY ./default.conf  /etc/nginx/conf.d/default.conf

COPY --from=node /usr/src/app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]