version: '3'
services:
  mgdb:
    image: mongo:latest
    restart: always
    ports:
      - '27018:27017'

  pgdb:
    image: postgres:latest
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6380:6379

  rabbit:
    image: rabbitmq:3.8.5-management
    container_name: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - '5672'
      - '15672'
    restart: always
