version: '3'
services:
  #mgdb접속 후 mongosh /usr/src/config/set.js 입력하면 레플리카셋 설정
  mgdb:
    image: mongo:latest
    depends_on:
      - mgdb2
      - mgdb3
    volumes:
      - ./db.setting/mgdb.repl.config:/usr/src/config
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - 27018:27017

  mgdb2:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - 27019:27017

  mgdb3:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - 27020:27017

  pgdb:
    image: postgres:latest
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6380:6379

  rabbit:
    image: rabbitmq:3.8.5-management
    container_name: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    expose:
      - '5672'
      - '15672'
    restart: always
