version: '3'
services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client/src:/usr/src/app/src:z
      - ./client/public:/usr/src/app/public:z
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  main-back:
    image: main-back
    build:
      context: ./server/main-back
      dockerfile: Dockerfile
    container_name: main-back
    volumes:
      - ./server/main-back/src:/usr/src/app/src:z
    ports:
      - '4000:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development

  sub-back:
    image: sub-back
    build:
      context: ./server/sub-back
      dockerfile: Dockerfile
    container_name: sub-back
    volumes:
      - ./server/sub-back/src:/usr/src/app/src:z
    ports:
      - '4001:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
      - MONGO_URI=mongodb://mgdb:27017/alert

  post:
    image: post
    build:
      context: ./server/post
      dockerfile: Dockerfile
    container_name: post
    volumes:
      - ./server/post/src:/usr/src/app/src:z
    ports:
      - '4005:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
      - MONGO_URI=mongodb://mgdb:27017/alert

  upload:
    image: upload
    build:
      context: ./server/upload
      dockerfile: Dockerfile
    container_name: upload
    volumes:
      - ./server/upload/src:/usr/src/app/src:z
    ports:
      - '4002:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=snsupload;AccountKey=sVDkSKQZyQPURSTGJrDoCOjizHGlaiRdgCwC00qqBggymMWDqWH49aslc8tVLX9VIrZW7r6B2f/Z+AStBA649Q==;EndpointSuffix=core.windows.net

  metadata:
    image: metadata
    build:
      context: ./server/metadata
      dockerfile: Dockerfile
    container_name: metadata
    volumes:
      - ./server/metadata/src:/usr/src/app/src:z
    ports:
      - '4003:80'
    environment:
      - MONGO_URI=mongodb://mgdb:27017/metadata
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development

  alert:
    image: alert
    build:
      context: ./server/alert
      dockerfile: Dockerfile
    container_name: alert
    volumes:
      - ./server/alert/src:/usr/src/app/src:z
    ports:
      - '4004:80'
    environment:
      - MONGO_URI=mongodb://mgdb:27017/alert
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
