version: '3'
services:
  mgdb:
    image: mongo
    restart: always
    ports:
      - '27018:27017'

  pgdb:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: '1234'

  redis:
    image: redis
    restart: always
    ports:
      - 6380:6379
