version: '3'
services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client/src:/usr/src/app/src:z
      - ./client/public:/usr/src/app/public:z
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'

  main-back:
    image: main-back
    build:
      context: ./server/main-back
      dockerfile: Dockerfile
    container_name: main-back
    volumes:
      - ./server/main-back/src:/usr/src/app/src:z
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development

  upload:
    image: upload
    build:
      context: ./server/upload
      dockerfile: Dockerfile
    container_name: upload
    volumes:
      - ./server/upload/src:/usr/src/app/src:z
    ports:
      - '4001:4001'
    environment:
      - NODE_ENV=development
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=firstkuberstorage;AccountKey=S6BuUU12Y0Cy+s6hDFnHwnKzrgnnUOJ80YOI+i6tSPJt4wnBDNEgw/Aw5rGjqmK1hZXDJHxumVNn+AStov8++g==;EndpointSuffix=core.windows.net
