version: '3'
services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client/src:/usr/src/app/src:z
      - ./client/public:/usr/src/app/public:z
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  main-back:
    image: main-back
    build:
      context: ./server/main-back
      dockerfile: Dockerfile
    container_name: main-back
    volumes:
      - ./server/main-back/src:/usr/src/app/src:z
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - NODE_ENV=development
