version: '3'
services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client
    volumes:
      - ./client/src:/usr/src/app/src:z
      - ./client/public:/usr/src/app/public:z

    environment:
      - NODE_ENV=development

  gateway:
    image: gateway
    build:
      context: ./server/gateway
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - ./server/gateway/src:/usr/src/app/src:z
    ports:
      - '4000:80'
    environment:
      - NODE_ENV=development

  upload:
    image: upload
    build:
      context: ./server/upload
      dockerfile: Dockerfile
    container_name: upload
    volumes:
      - ./server/upload/src:/usr/src/app/src:z
    ports:
      - '4001:80'
    environment:
      - NODE_ENV=development
      -

  monstache:
    restart: always
    image: rwynn/monstache:rel6
    command: -f /usr/src/mons.config.toml &
    volumes:
      - ./db/mons.config.toml:/usr/src/mons.config.toml
    ports:
      - '8089:8080'
