version: '3'
services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client/src:/usr/src/app/src:z
      - ./client/public:/usr/src/app/public:z
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  gateway:
    image: gateway
    build:
      context: ./server/gateway
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - ./server/gateway/src:/usr/src/app/src:z
    ports:
      - '4000:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
      - MONGO_URI=mongodb://mgdb:27017/sns

  upload:
    image: upload
    build:
      context: ./server/upload
      dockerfile: Dockerfile
    container_name: upload
    volumes:
      - ./server/upload/src:/usr/src/app/src:z
    ports:
      - '4001:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=snsupload;AccountKey=sVDkSKQZyQPURSTGJrDoCOjizHGlaiRdgCwC00qqBggymMWDqWH49aslc8tVLX9VIrZW7r6B2f/Z+AStBA649Q==;EndpointSuffix=core.windows.net
