version: '3'
services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./client/src:/usr/src/app/src:z
      - ./client/public:/usr/src/app/public:z
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  gateway:
    image: gateway
    build:
      context: ./server/gateway
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
      - ./server/gateway/src:/usr/src/app/src:z
    ports:
      - '4000:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development

  user:
    image: user
    build:
      context: ./server/user
      dockerfile: Dockerfile
    container_name: user
    volumes:
      - ./server/user/src:/usr/src/app/src:z
    ports:
      - '4001:80'
      - '4002:81'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development

  ffl:
    image: ffl
    build:
      context: ./server/ffl
      dockerfile: Dockerfile
    container_name: ffl
    volumes:
      - ./server/ffl/src:/usr/src/app/src:z
    ports:
      - '4003:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
      - MONGO_URI=mongodb://mgdb:27017/ffl

  post:
    image: post
    build:
      context: ./server/post
      dockerfile: Dockerfile
    container_name: post
    volumes:
      - ./server/post/src:/usr/src/app/src:z
    ports:
      - '4004:80'
      #- '40004:3000'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development

  upload:
    image: upload
    build:
      context: ./server/upload
      dockerfile: Dockerfile
    container_name: upload
    volumes:
      - ./server/upload/src:/usr/src/app/src:z
    ports:
      - '4005:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=snsupload;AccountKey=sVDkSKQZyQPURSTGJrDoCOjizHGlaiRdgCwC00qqBggymMWDqWH49aslc8tVLX9VIrZW7r6B2f/Z+AStBA649Q==;EndpointSuffix=core.windows.net

  metadata:
    image: metadata
    build:
      context: ./server/metadata
      dockerfile: Dockerfile
    container_name: metadata
    volumes:
      - ./server/metadata/src:/usr/src/app/src:z
    ports:
      - '4006:80'
    environment:
      - MONGO_URI=mongodb://mgdb:27017/metadata
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development

  alert:
    image: alert
    build:
      context: ./server/alert
      dockerfile: Dockerfile
    container_name: alert
    volumes:
      - ./server/alert/src:/usr/src/app/src:z
    ports:
      - '4007:80'
    environment:
      - MONGO_URI=mongodb://mgdb:27017/alert
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development

  live-search:
    image: live-search
    build:
      context: ./server/live-search
      dockerfile: Dockerfile
    container_name: live-search
    volumes:
      - ./server/live-search/src:/usr/src/app/src:z
    ports:
      - '4008:80'
    environment:
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
